test_that("imageSet labels from file names, vectors or functions", {
  paths <- c("/x/1948-1950.png", "/x/1967.png", "/x/1967_alt.png")
  s <- imageSet(paths)
  expect_equal(s$id, c("1948-1950", "1967", "1967_alt"))
  expect_equal(s$label, s$id)
  expect_equal(imageSet(paths, label = function(x) sub("_.*$", "", x))$label, c("1948-1950", "1967", "1967"))
  expect_equal(imageSet(paths, label = c("a", "b", "b"))$label, c("a", "b", "b"))
  expect_error(imageSet(paths, label = c("a", "b")), "length")
})

test_that("imageMime reads magic bytes and imageMeta makes data URIs", {
  png <- tempfile(fileext = ".png")
  png::writePNG(array(runif(4 * 4 * 3), c(4, 4, 3)), png)
  jpg <- tempfile(fileext = ".jpg")
  jpeg::writeJPEG(array(runif(4 * 4 * 3), c(4, 4, 3)), jpg)
  txt <- tempfile(fileext = ".txt"); writeLines("hi", txt)
  expect_equal(imageMime(png), "image/png")
  expect_equal(imageMime(jpg), "image/jpeg")
  expect_true(is.na(imageMime(txt)))
  m <- imageMeta(c(png, jpg), ids = c("a", "b"))
  expect_equal(m$key, c("image_a", "image_b"))
  expect_match(m$value[1], "^data:image/png;base64,")
  expect_match(m$value[2], "^data:image/jpeg;base64,")
  expect_error(imageMeta(txt), "not an image")
})

test_that("the synthetic fixture has the promised shapes", {
  v <- syntheticVision()
  expect_equal(dim(v$patches), c(6, 9, 8))
  expect_equal(nrow(v$images), 6)
  expect_equal(unname(round(sqrt(rowSums(v$image^2)), 6)), rep(1, 6))
})

test_that("imageSet reads a folder and labels by subfolder", {
  root <- tempfile("pics"); dir.create(file.path(root, "cardinal"), recursive = TRUE); dir.create(file.path(root, "robin"))
  img <- array(runif(4 * 4 * 3), c(4, 4, 3))
  png::writePNG(img, file.path(root, "cardinal", "1.png"))
  jpeg::writeJPEG(img, file.path(root, "cardinal", "2.JPG"))
  png::writePNG(img, file.path(root, "robin", "1.png"))
  writeLines("notes", file.path(root, "robin", "notes.txt"))
  s <- imageSet(root)
  expect_equal(nrow(s), 3)
  expect_equal(s$label, c("cardinal", "cardinal", "robin"))
  # shared file names get their folder in front, so ids stay unique
  expect_equal(s$id, c("cardinal_1", "2", "robin_1"))
  expect_true(all(file.exists(s$path)))
  expect_equal(imageSet(root, label = c("a", "a", "b"))$label, c("a", "a", "b"))
})

test_that("imageSet labels a flat folder by file name and rejects an empty one", {
  root <- tempfile("flat"); dir.create(root)
  expect_error(imageSet(root), "No image files")
  img <- array(runif(4 * 4 * 3), c(4, 4, 3))
  png::writePNG(img, file.path(root, "robin_a.png")); png::writePNG(img, file.path(root, "wren_a.png"))
  expect_equal(imageSet(root)$label, c("robin_a", "wren_a"))
  expect_equal(imageSet(root, label = function(x) sub("_.*$", "", x))$label, c("robin", "wren"))
})

test_that("imageSet warns about a mixed layout and rejects a missing folder", {
  root <- tempfile("mixed"); dir.create(file.path(root, "robin"), recursive = TRUE)
  img <- array(runif(4 * 4 * 3), c(4, 4, 3))
  png::writePNG(img, file.path(root, "robin", "1.png")); png::writePNG(img, file.path(root, "loose.png"))
  expect_warning(s <- imageSet(root), "subfolders")
  expect_equal(sort(s$label), c("1", "loose"))
  expect_error(imageSet(file.path(root, "no_such_dir")), "No such folder")
})

test_that("the example photos that ship with moose are labelled by folder", {
  pics <- system.file("extdata", "pics", package = "moose")
  s <- imageSet(pics)
  expect_equal(nrow(s), 36)
  expect_equal(as.vector(table(s$label)), rep(6L, 6))
  expect_setequal(s$label, c("banana", "blueberry", "kiwi", "lemon", "pineapple", "strawberry"))
  expect_false(anyDuplicated(s$id) > 0)
  expect_true(all(vapply(s$path, imageMime, "") == "image/jpeg"))
  expect_length(list.files(system.file("extdata", "new-photos", package = "moose")), 6)
})
